language: node_js

env:
  global:
    - PLATFORM=linux
  matrix:
    - LUA=lua5.1
    - LUA=luajit

before_install:
    - git clone https://github.com/luvit/luvit.git --recursive
    - cd luvit
    - make
    - make test

node_js:
  - "0.10"
